### ISSUE TITLE
Ycashd daemon crashes

### ISSUE THREAD

**Issue by pinpins** [ycashfoundation/ycash#30]
ycashd crashes with below error on ubuntu 16.04

` ycashd: wallet/wallet.cpp:1066: void CopyPreviousWitnesses(NoteDataMap&, int, int64_t) [with NoteDataMap = std::map<SaplingOutPoint, SaplingNoteData>; int64_t = long int]: Assertion `(nd->witnessHeight == -1) || (nd->witnessHeight == indexHeight - 1)' failed.
`

**Comment by hloo** [comment]
This is due to upstream [Zcash Issue #4301](https://github.com/zcash/zcash/issues/4301). We have incorporated the upstream changes thought to fix this, but the problem remains in Ycash, and we believe that it actually still remains in the Zcash master branch (see this comment: https://forum.zcashcommunity.com/t/zecwallet-fullnode-0-9-5-could-not-connect-to-zcashd/36180/16?u=hloo).

A full reindex will fix this problem, but we know that it is a pain to do a reindex, so as soon as this is definitively fixed upstream, we will issue a new release with the new upstream fix.

**Comment by hloo** [comment]
Fixed in v2.1.1.5. For more information, see [ycashd v2.1.1.5 release notes](https://github.com/ycashfoundation/ycash/releases/tag/2.1.1-5).
